# Generated by Django 2.2.1 on 2019-06-01 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_filename', models.FilePathField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('pixel_size', models.IntegerField()),
                ('iteration_number', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('signal_input', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userint.SignalInput')),
            ],
        ),
    ]
