# Generated by Django 2.2.1 on 2019-06-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0002_signaloutput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaloutput',
            name='owner',
        ),
    ]
