# Generated by Django 2.2.1 on 2019-06-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0003_remove_signaloutput_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaloutput',
            name='signal_input',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='userint.SignalInput'),
        ),
    ]
